import { IconType } from "react-icons";
import {
  HiArrowRight,
  HiArrowTopRightOnSquare,
  HiArrowUpRight,
  HiCalendarDays,
  HiEnvelope,
  HiOutlineDocument,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineLink,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";
import {
  PiBookBookmarkDuotone,
  PiGridFourDuotone,
  PiHouseDuotone,
  PiImageDuotone,
  PiUserCircleDuotone,
} from "react-icons/pi";
import {
  FaBootstrap,
  FaCss3,
  FaDiscord,
  FaDocker,
  FaGithub,
  FaGolang,
  FaHtml5,
  FaJava,
  FaLinkedin,
  FaNodeJs,
  FaNpm,
  FaPython,
  FaReact,
  FaThreads,
  FaTwitch,
  FaUnity,
  FaX,
  FaAws,
} from "react-icons/fa6";
import { RiNextjsFill, RiTailwindCssFill } from "react-icons/ri";
import {
  BiLogoDjango,
  BiLogoPostgresql,
  BiLogoTypescript,
} from "react-icons/bi";
import { IoLogoJavascript, IoLogoElectron } from "react-icons/io5";
import {
  SiApachemaven,
  SiD3Dotjs,
  SiEclipseide,
  SiExpress,
  SiI18Next,
  SiMongodb,
  SiRedux,
  SiRubyonrails,
  SiSelenium,
  SiSpigotmc,
  SiVite,
  SiWebgl,
  SiWebpack,
} from "react-icons/si";
import { TbBrandCSharp } from "react-icons/tb";
import { DiVisualstudio, DiRuby } from "react-icons/di";
import { VscAzure } from "react-icons/vsc";

const techStackIcons: Record<string, IconType> = {
  aws: FaAws,
  azure: VscAzure,
  bootstrap: FaBootstrap,
  csharp: TbBrandCSharp,
  css: FaCss3,
  d3: SiD3Dotjs,
  django: BiLogoDjango,
  docker: FaDocker,
  eclipse: SiEclipseide,
  electron: IoLogoElectron,
  express: SiExpress,
  golang: FaGolang,
  html: FaHtml5,
  i18next: SiI18Next,
  java: FaJava,
  javascript: IoLogoJavascript,
  maven: SiApachemaven,
  mongodb: SiMongodb,
  next: RiNextjsFill,
  node: FaNodeJs,
  npm: FaNpm,
  postgresql: BiLogoPostgresql,
  python: FaPython,
  rails: SiRubyonrails,
  react: FaReact,
  redux: SiRedux,
  ruby: DiRuby,
  selenium: SiSelenium,
  spigot: SiSpigotmc,
  tailwind: RiTailwindCssFill,
  twitch: FaTwitch,
  typescript: BiLogoTypescript,
  unity: FaUnity,
  visualstudio: DiVisualstudio,
  vite: SiVite,
  webgl: SiWebgl,
  webpack: SiWebpack,
};

export const iconLibrary: Record<string, IconType> = {
  arrowRight: HiArrowRight,
  arrowUpRight: HiArrowUpRight,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  book: PiBookBookmarkDuotone,
  calendar: HiCalendarDays,
  discord: FaDiscord,
  document: HiOutlineDocument,
  email: HiEnvelope,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  gallery: PiImageDuotone,
  github: FaGithub,
  globe: HiOutlineGlobeAsiaAustralia,
  grid: PiGridFourDuotone,
  home: PiHouseDuotone,
  linkedin: FaLinkedin,
  openLink: HiOutlineLink,
  person: PiUserCircleDuotone,
  rocket: HiOutlineRocketLaunch,
  threads: FaThreads,
  x: FaX,
  ...techStackIcons,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
